### ISSUE TITLE
bug: dead links

### ISSUE THREAD

**Issue by allanice001** [GlueOps/glueops-dev#23]
https://github.com/GlueOps/glueops-dev/blob/1b2910bf6555294cdbb9fdc3d327f891b608872f/src/components/hero-glueops.tsx#L25

Should this link to https://glueops.dev/docs/introduction ??

**Comment by venkatamutyala** [comment]
More 404s:

<img width="1234" alt="image" src="https://github.com/GlueOps/glueops-dev/assets/6570292/a2c9d5a8-df08-4168-aa25-2119cdc1d5c3">
